### ISSUE TITLE
No support for newer versions

### ISSUE THREAD

**Issue by jankyv** [webcraft/lunar-mollie#1]
I just upgraded to Lunar ^0.6. The composer requirements however do not meet that version yet.

**Comment by webcraft** [comment]
Thanks! Going to fix that very soon, probably tomorrow!

**Comment by sanneterpstra** [comment]
Lunar ^0.7 just released so this issue came up again when trying to upgrade Lunar.

**Comment by webcraft** [comment]
Thanks @sanneterpstra, fixed in #[f24b071](https://github.com/webcraft/lunar-mollie/commit/f24b0710cd6c8019cbfd3c5419b6acb13a96ea83)

**Comment by sanneterpstra** [comment]
Hi @webcraft I was wondering if support for ^1.0 beta is possible? I'm in the process of upgrading my webshop to Lunar 1.0 and this package is the only one that is holding this back.

**Comment by webcraft** [comment]
Hi @sanneterpstra, I haven't looked at the 1.0 branch in a while, so not sure if it requires many changes to this package. I can have a look at it when things are a bit calmer for me, I hope in a few weeks. If you'd like to submit a PR in the meantime, that would also help speed things up of course.

**Comment by sanneterpstra** [comment]
#2 Done! 😃

**Comment by webcraft** [comment]
Thank you very much for the PR @sanneterpstra 

I merged it, but I was a bit too fast. The tests are failing right now. It seems the Http::fake() doesn't have any effect anymore, and the call is done to the real Mollie endpoint instead of the fake one. Will have a closer look tomorrow. When it's fixed, I'll tag a new release.
